sudo: required
services: 
  - docker

before_install: 
  - docker build -t ailoen/docker-react -f Dockerfile.dev . 

script: 
  - docker run -e CI=true ailoen/docker-react npm run test

language: generic